### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by charlescabbage** [Mespeon/Sample-Repo#1]
I ran helloworld.py and got a BSOD! na-delete system32 ko wtf virus to!

jk lang bro xD

**Comment by Mespeon** [comment]
HAHAHA sorry bro, ginamit ko kasing material sa teaching class ko hahahaha!

Pa-install na lang ulit ng Windows. xD

Ingats brooo!



Best regards,
  Mark Edriane Nolledo
  Mobile: +639053999038Sent via GMail for browsers using Microsoft Chromium
Edge <https://www.microsoft.com/en-us/edge>.
